### ISSUE TITLE
Primera pagina

### ISSUE THREAD

**Issue by rivalcoba** [rivalcoba/t3-meal-app#10]
Se trata de crear la página principal de acuerdo a la maqueta acordada.

**Comment by rivalcoba** [comment]
Para integrar en proyecti
`git fetch origin`
`git checkout 10-primera-pagina`

**Comment by carlareyesgo** [comment]
Ya está la maquetación :)

**Comment by carlareyesgo** [comment]
Ya actualicé el index :D

**Comment by rivalcoba** [comment]
Concluida.
