### ISSUE TITLE
Ordenamiento de tarjetas de resultados

### ISSUE THREAD

**Issue by rivalcoba** [rivalcoba/t3-meal-app#14]
Este issue consiste en aplicar el ordenamiento y disposición de las tarjetas que mostrarán los resultados de la búsqueda.

**Comment by rivalcoba** [comment]
Para crear la tanda asociada al issue localmente
git fetch origin
git checkout 14-ordenamiento-de-tarjetas-de-resultados

**Comment by albeey** [comment]
Termine con el ordenamiento de tarjetas utilizando CSS Grid y añadí un poco de estilo y efectos, estos pueden ser cambiados o ajustados según sea necesario @rivalcoba

**Comment by rivalcoba** [comment]
concluida
