### ISSUE TITLE
Instalar y configurar Webpack Dev Server.

### ISSUE THREAD

**Issue by rivalcoba** [rivalcoba/t3-meal-app#2]
Este issue trata de Instalar y configurar webpack dev server una vez que se ha instalado y configurado webpack.

**Comment by rivalcoba** [comment]
@barsaiz19 Puedes trabajar el issue en este branch
`git fetch origin`
`git checkout 2-instalar-y-configurar-webpack-dev-server`

**Comment by isbaruc** [comment]
Acabo de enviar el pull request #6

**Comment by rivalcoba** [comment]
Se cierra el issue
