### ISSUE TITLE
Instalar Babel

### ISSUE THREAD

**Issue by rivalcoba** [rivalcoba/t3-meal-app#4]
Instalar y configurar babel junto con webpack

**Comment by rivalcoba** [comment]
@carlareyesgo por favor realiza la instalación de babel, gracias de antemano
`git fetch origin`
`git checkout 4-instalar-babel`

**Comment by carlareyesgo** [comment]
Listo, puedes checarlo, por favor?

**Comment by rivalcoba** [comment]
@carlareyesgo falta agregar los cargadores al archivo de [configuracion de webpack](https://github.com/rivalcoba/t3-meal-app/blob/4-instalar-babel/webpack.config.js) asi:
```javascript
module: {
    rules: [
      { test: /\.css$/, use: ['style-loader', 'css-loader'] },
      // 👇👇👇 Cargador de webpack 👇👇👇
      {
        test: /\.m?js$/,
        exclude: /node_modules/,
        use: {
          loader: "babel-loader",
          options: {
            presets: ['@babel/preset-env']
          }
        }
      },
    ]
  },
```

**Comment by carlareyesgo** [comment]
listo, checalo por favor :)

**Comment by rivalcoba** [comment]
@carlareyesgo Hay un problema, en tu commit borraste la parte que carga los assets e imagenes.
```javascript
      {
        test: /\.(png|jpe?g|gif|svg|eot|ttf|woff|woff2)$/i,
        // More information here https://webpack.js.org/guides/asset-modules/
        type: "asset",
      },
```
Hay que regresarla por que si no dejara de funcionar la carga de assets en el proyecto.

**Comment by carlareyesgo** [comment]
Listo, ya lo volví a agregar :)

**Comment by rivalcoba** [comment]
@carlareyesgo Genial, nada mas solicita tu Pull Reques y ponme como revisor.

**Comment by rivalcoba** [comment]
Se da por concluido este issue ya se ha fusionado con la rama dev
